### ISSUE TITLE
Notice: Undefined offset: 1

### ISSUE THREAD

**Issue by sin2384** [claudiosanches/social-count-plus#41]
Hi Claudio,

from time to time I get this error: 
Notice: Undefined offset: 1 in wp-content/plugins/social-count-plus/includes/counters/class-social-count-plus-pinterest-counter.php on line 63

After page refresh, the error is gone. This probably happens when transients expire.

Maybe you should do something like this:
`$count = isset( $tags[1] ) ? intval( $tags[1] ) : 0;`

Regards,
Sinisa

**Comment by claudiosanches** [comment]
But this should generate the new transient... If not will save as `0` like in your example.
Maybe you are using an incorrect username on the settings.
